port: "8888"

db:
    host: "localhost"
    port: "5432"
    user: "postgres"
    dbname: "mytask"
    sslmode: "disable"

cache:
    defaultExpiration: 5000
    cleanupInterval: 10000
    expiration: 5000
    refreshDuration: 5000