port: "8888"

db:
    host: "localhost"
    port: "5432"
    user: "postgres"
    dbname: "mytask"
    sslmode: "disable"

cache:
    defaultExpiration: 600000000
    cleanupInterval: 1000000
    expiration: 600000000
    refreshDuration: 500000000